#!/usr/bin/env bash
set -euo pipefail

SDK=$(xcrun --show-sdk-path)
HEADER="$SDK/usr/include/mach/vm_statistics.h"

[[ -f "$HEADER" ]] || { echo "error: $HEADER not found" >&2; exit 1; }

OUT="src/region_tag.rs"

{
  echo "// generated by generate_region_tags.sh — do not edit manually"
  echo "// source: $HEADER"
  echo ""
  echo "pub fn region_tag(tag: u32) -> String {"
  echo "    match tag {"

  grep '^\s*#define VM_MEMORY_' "$HEADER" \
    | awk '{print $2, $3}' \
    | grep -E '^VM_MEMORY_[A-Z_]+ [0-9]+$' \
    | sort -k2 -n \
    | awk '{
        name = tolower($1)
        sub(/^vm_memory_/, "", name)
        printf "        %s => \"%s\",\n", $2, name
      }'

  echo "        _ => \"other\","
  echo "    }.to_owned()"
  echo "}"
} > "$OUT"

echo "written: $OUT"
